---
title: "Lab 9"
author: "Prithviraj Kadiyala"
date: "October 15, 2018"
output:
  html_document:
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Task 1
```{r}
getwd()
```

#Task 2
## Code Analysis
```
A. Create a sample with replacement and prob is not given because it is uniform.
B. Calculating the confidence intervals for the given data.
```

##Equal probability
```
Question : As used in the myboot() function, each datum in x will be selected with equal probability. Why is this necessary?
```

```
Answer : Since the data is uniform having given no probability. The samples can be created with uniform distribution.
```

##Replace=TRUE
```{r}
set.seed(35)
sam=round(rnorm(20,mean=10,sd=4),2)
unique(sample(sam,20,replace=TRUE))
unique(sample(sam,20,replace=TRUE))
unique(sample(sam,20,replace=TRUE))
unique(sample(sam,20,replace=TRUE))
unique(sample(sam,20,replace=TRUE))
```

```
We get a set of unique sample when we run the line each time
```

##Replace=FALSE
```{r}
unique(sample(sam,20,replace=FALSE))
unique(sample(sam,20,replace=FALSE))
unique(sample(sam,20,replace=FALSE))
unique(sample(sam,20,replace=FALSE))
unique(sample(sam,20,replace=FALSE))
```

```
The sample set we get each time is same. Just re-arranged.
```

##21 sample
```
unique(sample(sam,21,replace=FALSE))
```

```
It says cannot take a larger sample than the population
```

#Task 3

##myboot2() function
```{r}
myboot2<-function(iter=10000,x,fun="mean",alpha=0.05,cx=1.5,...){  #Notice where the ... is repeated in the code
n=length(x)   #sample size

y=sample(x,n*iter,replace=TRUE)
rs.mat=matrix(y,nr=n,nc=iter,byrow=TRUE)
xstat=apply(rs.mat,2,fun) # xstat is a vector and will have iter values in it 
ci=quantile(xstat,c(alpha/2,1-alpha/2))# Nice way to form a confidence interval
# A histogram follows
# The object para will contain the parameters used to make the histogram
para=hist(xstat,freq=FALSE,las=1,
main=paste("Histogram of Bootstrap sample statistics","\n","alpha=",alpha," iter=",iter,sep=""),
...)

#mat will be a matrix that contains the data, this is done so that I can use apply()
mat=matrix(x,nr=length(x),nc=1,byrow=TRUE)

#pte is the point estimate
#This uses whatever fun is
pte=apply(mat,2,fun)
abline(v=pte,lwd=3,col="Black")# Vertical line
segments(ci[1],0,ci[2],0,lwd=4)      #Make the segment for the ci
text(ci[1],0,paste("(",round(ci[1],2),sep=""),col="Red",cex=cx)
text(ci[2],0,paste(round(ci[2],2),")",sep=""),col="Red",cex=cx)

# plot the point estimate 1/2 way up the density
text(pte,max(para$density)/2,round(pte,2),cex=cx)

return(list(ci=ci,fun=fun,x=x))# Some output to use if necessary
}
```

##Alpha=95%
```{r}
set.seed(39); sam=rnorm(25,mean=25,sd=10)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.05,xlab="mean(x)",col="Blue",cx=1.5)

set.seed(30); sam=rchisq(20,df=3)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.05,xlab="mean(x)",col="Blue",cx=1.5)

set.seed(40); sam=rgamma(30,shape=2,scale=3)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.05,xlab="mean(x)",col="Blue",cx=1.5)

set.seed(10); sam=rbeta(20,shape1=3,shape2=4)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.05,xlab="mean(x)",col="Blue",cx=1.5)
```


##Point Estimate
```{r}
abs(25-23.88)*100/25
abs(3-2.94)*100/3
abs(6-6.5)*100/6
abs(0.4286-0.41)*100/0.4286
```
 
##Alpha=80%
```{r}
set.seed(39); sam=rnorm(25,mean=25,sd=10)
myboot2(10000,x=sam,fun=function(x) var(x),alpha=0.20,xlab="var(x)",col="Blue",cx=1.5)

set.seed(30); sam=rchisq(20,df=3)
myboot2(10000,x=sam,fun=function(x) var(x),alpha=0.20,xlab="var(x)",col="Blue",cx=1.5)

set.seed(40); sam=rgamma(30,shape=2,scale=3)
myboot2(10000,x=sam,fun=function(x) var(x),alpha=0.20,xlab="var(x)",col="Blue",cx=1.5)

set.seed(10); sam=rbeta(20,shape1=3,shape2=4)
myboot2(10000,x=sam,fun=function(x) var(x),alpha=0.20,xlab="var(x)",col="Blue",cx=1.5)
```

#Task 4
##myboot2() edited
```{r}
myboot21<-function(iter=10000,x,fun="mean",alpha=0.05,...){  #Notice where the ... is repeated in the code
  n=length(x)   #sample size
  
  y=sample(x,n*iter,replace=TRUE)
  rs.mat=matrix(y,nr=n,nc=iter,byrow=TRUE)
  xstat=apply(rs.mat,2,fun) # xstat is a vector and will have iter values in it 
  ci=quantile(xstat,c(alpha/2,1-alpha/2))# Nice way to form a confidence interval
  # A histogram follows
  # The object para will contain the parameters used to make the histogram
  para=hist(xstat,freq=FALSE,las=1,
            main=paste("Histogram of Bootstrap sample statistics","\n","alpha=",alpha," iter=",iter,sep=""),
            ...)
  
  #mat will be a matrix that contains the data, this is done so that I can use apply()
  mat=matrix(x,nr=length(x),nc=1,byrow=TRUE)
  
  #pte is the point estimate
  #This uses whatever fun is
  pte=apply(mat,2,fun)
  abline(v=pte,lwd=3,col="Black")# Vertical line
  segments(ci[1],0,ci[2],0,lwd=4)      #Make the segment for the ci
  text(ci[1],0,paste("(",round(ci[1],2),sep=""),col="Red",cex=1)
  text(ci[2],0,paste(round(ci[2],2),")",sep=""),col="Red",cex=1)
  
  # plot the point estimate 1/2 way up the density
  text(pte,max(para$density)/2,round(pte,2),cex=1)
  
  m=mean(x)
  return(list(ci=ci,fun=fun,m=m,xstat=xstat))# Some output to use if necessary
}
```

##Barplot
```{r}
#barplot of xstat
sam=c(1,1,1,2,2,2,2,3,3,3,4,4) 
data=myboot21(100,x=sam,fun="median" ,alpha=0.05,xlab="median(x)",col="Blue")
barplot(data$xstat, main="Barplot of xstat",col="Blue")
```

##(L,U)
```
From the graph (L,U) = (1.5,3)
```

#Task 5
##Alpha=95%
```{r}
set.seed(39); sam=rnorm(25,mean=25,sd=10)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.05,xlab="mean(x)/median(x)",col="Green",cx=1.5)

set.seed(30); sam=rchisq(20,df=3)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.05,xlab="mean(x)/median(x)",col="Green",cx=1.5)

set.seed(40); sam=rgamma(30,shape=2,scale=3)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.05,xlab="mean(x)/median(x)",col="Green",cx=1.5)

set.seed(10); sam=rbeta(20,shape1=3,shape2=4)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.05,xlab="mean(x)/median(x)",col="Green",cx=1.5) 
```

##Alpha=70%
```{r}
set.seed(39); sam=rnorm(25,mean=25,sd=10)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.3,xlab="mean(x)/median(x)",col="Green",cx=1.5)

set.seed(30); sam=rchisq(20,df=3)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.3,xlab="mean(x)/median(x)",col="Green",cx=1.5)

set.seed(40); sam=rgamma(30,shape=2,scale=3)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.3,xlab="mean(x)/median(x)",col="Green",cx=1.5)

set.seed(10); sam=rbeta(20,shape1=3,shape2=4)
myboot2(10000,x=sam,fun=function(x) mean(x)/median(x),alpha=0.3,xlab="mean(x)/median(x)",col="Green",cx=1.5) 
```

#Task 6
##Distributions
```{r}
?distributions
```

##samples
###Cauchy
```{r}
sam = rcauchy(20, 2, 2)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.20,xlab="mean(x)",col="Red",cx=1.5)
myboot2(10000,x=sam,fun=function(x) median(x),alpha=0.20,xlab="median(x)",col="Red",cx=1.5)
```

###Hyper geometric
```{r}
sam = rhyper(30, 4, 6, 4)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.20,xlab="mean(x)",col="Green",cx=1.5)
myboot2(10000,x=sam,fun=function(x) median(x),alpha=0.20,xlab="median(x)",col="Green",cx=1.5)
```


###Poisson
```{r}
sam = rpois(25, 4)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.20,xlab="mean(x)",col="Blue",cx=1.5)
myboot2(10000,x=sam,fun=function(x) median(x),alpha=0.20,xlab="median(x)",col="Blue",cx=1.5)
```


###Weibull
```{r}
sam = rweibull(30, 3, 2)
myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.20,xlab="mean(x)",col="Purple",cx=1.5)
myboot2(10000,x=sam,fun=function(x) median(x),alpha=0.20,xlab="median(x)",col="Purple",cx=1.5)
```


#Task 7
##sd and quantile
```{r}
set.seed(68)
sam=rnorm(20,mean=10,sd=4) 
myboot2(10000,x=sam,fun=function(x) sd(x),alpha=0.05,xlab="sd(x)",col="Orange",cx=1.5)
myboot2(10000,x=sam,fun=function(x) quantile(x),alpha=0.05,xlab="quantile(x)",col="Orange",cx=1.5)
```


##calculating the mean
```{r}
alpha2 = qnorm(1-(.05/2),mean=0,sd=1)
left = mean(sam) - alpha2*(4/sqrt(20))
right = mean(sam) + alpha2*(4/sqrt(20))
left
right
```


##mean
```{r}
set.seed(68)
sam=rnorm(20,mean=10,sd=4)
data=myboot2(10000,x=sam,fun=function(x) mean(x),alpha=0.05,xlab="mean(x)",col="Orange",cx=1.5)
data$ci
```


##Comparison
```
The two intervals are very close
```

















